### ISSUE TITLE
Warning with StepZ80 function.

### ISSUE THREAD

**Issue by jwpyle3** [jkingsman/ArduinoMegaZ80Core#1]
I keeps getting the following warning when compiling.  It doesn't seem effect anything and still runs fine.  Just wording if I need to make any changes to it.

/Arduino/libraries/Z80/src/Z80.c: In function 'StepZ80':
/Arduino/libraries/Z80/src/Z80.c:720:34: warning: 'return' with a value, in function returning void
     if(!(R->IFF&IFF_EI)) return(R->ICount);
                                ~~^~~~~~~~~
/Arduino/libraries/Z80/src/Z80.c:691:6: note: declared here
 void StepZ80(register Z80 *R)
      ^~~~~~~

James

**Comment by jkingsman** [comment]
Thanks for the heads up! 

Yeah looks like that should be an int to return the number of cycles run, but it doesn't always return one. It's safe to ignore!
