### ISSUE TITLE
External Memory

### ISSUE THREAD

**Issue by fredcwbr** [jkingsman/ArduinoMegaZ80Core#3]
Howdy, 
Hope this gets you well.
First of all thanks for your work , and twinkling on the Z80 emulator to turn it into a  Z80Mega.

Found out of this project only yesterday, so just one question, . 
If I understood correctly, the Z80Read/Write Memory can use External Memory, if it is available and configured on the Mega2560, just by recoding the needed functon . ,

Thanks in advance, 

And best regards.

**Comment by jkingsman** [comment]
Yup! You can use whatever memory store you would like as long as you can write a function to associate stored data with an address (write) and return that data when that address is requested (read).

**Comment by fredcwbr** [comment]
Thanks for the update. 
Will do ., ,
Hope it can run CP/M ... 
Best Regards
